/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOgamexWatchListRouteImport } from './routes/api/public/ogamex-watch-list'
import { Route as ApiPublicSyncOgamexActivityRouteImport } from './routes/api/public/sync-ogamex-activity'
import { Route as ApiPublicSyncOgamexSystemRouteImport } from './routes/api/public/sync-ogamex-system'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgamexWatchListRoute =
  ApiPublicOgamexWatchListRouteImport.update({
    id: '/api/public/ogamex-watch-list',
    path: '/api/public/ogamex-watch-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncOgamexActivityRoute =
  ApiPublicSyncOgamexActivityRouteImport.update({
    id: '/api/public/sync-ogamex-activity',
    path: '/api/public/sync-ogamex-activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncOgamexSystemRoute =
  ApiPublicSyncOgamexSystemRouteImport.update({
    id: '/api/public/sync-ogamex-system',
    path: '/api/public/sync-ogamex-system',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/ogamex-watch-list': typeof ApiPublicOgamexWatchListRoute
  '/api/public/sync-ogamex-activity': typeof ApiPublicSyncOgamexActivityRoute
  '/api/public/sync-ogamex-system': typeof ApiPublicSyncOgamexSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/ogamex-watch-list': typeof ApiPublicOgamexWatchListRoute
  '/api/public/sync-ogamex-activity': typeof ApiPublicSyncOgamexActivityRoute
  '/api/public/sync-ogamex-system': typeof ApiPublicSyncOgamexSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/ogamex-watch-list': typeof ApiPublicOgamexWatchListRoute
  '/api/public/sync-ogamex-activity': typeof ApiPublicSyncOgamexActivityRoute
  '/api/public/sync-ogamex-system': typeof ApiPublicSyncOgamexSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/ogamex-watch-list'
    | '/api/public/sync-ogamex-activity'
    | '/api/public/sync-ogamex-system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/ogamex-watch-list'
    | '/api/public/sync-ogamex-activity'
    | '/api/public/sync-ogamex-system'
  id:
    | '__root__'
    | '/'
    | '/api/public/ogamex-watch-list'
    | '/api/public/sync-ogamex-activity'
    | '/api/public/sync-ogamex-system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicOgamexWatchListRoute: typeof ApiPublicOgamexWatchListRoute
  ApiPublicSyncOgamexActivityRoute: typeof ApiPublicSyncOgamexActivityRoute
  ApiPublicSyncOgamexSystemRoute: typeof ApiPublicSyncOgamexSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ogamex-watch-list': {
      id: '/api/public/ogamex-watch-list'
      path: '/api/public/ogamex-watch-list'
      fullPath: '/api/public/ogamex-watch-list'
      preLoaderRoute: typeof ApiPublicOgamexWatchListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-ogamex-activity': {
      id: '/api/public/sync-ogamex-activity'
      path: '/api/public/sync-ogamex-activity'
      fullPath: '/api/public/sync-ogamex-activity'
      preLoaderRoute: typeof ApiPublicSyncOgamexActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-ogamex-system': {
      id: '/api/public/sync-ogamex-system'
      path: '/api/public/sync-ogamex-system'
      fullPath: '/api/public/sync-ogamex-system'
      preLoaderRoute: typeof ApiPublicSyncOgamexSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicOgamexWatchListRoute: ApiPublicOgamexWatchListRoute,
  ApiPublicSyncOgamexActivityRoute: ApiPublicSyncOgamexActivityRoute,
  ApiPublicSyncOgamexSystemRoute: ApiPublicSyncOgamexSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
